---
apiVersion: v1
kind: Pod
metadata: 
  name: jenkins-container
spec:
  containers:
    - image: jenkins/jenkins:lts-jdk11
      name: jenkins-container
      ports:
       - containerPort: 8080
         hostIP: 54.71.5.126
         hostPort: 8082 

    - image: nginx
      name: apache1
      ports:
        - containerPort: 80
          hostPort: 8083
